apiVersion: v2
name: tasks-api
description: FastAPI microservice for managing tasks
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Yasmine Ben Hamada
    email: yasmine@example.com
