apiVersion: apps/v1
kind: Deployment
metadata:
  name: interns-api
  namespace: orbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interns-api
  template:
    metadata:
      labels:
        app: interns-api
    spec:
      containers:
      - name: interns-api
        image: orbit-platform-interns-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql:5432/orbit"
        - name: SPRING_DATASOURCE_USERNAME
          value: "orbit"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 800m
            memory: 1Gi
