apiVersion: apps/v1
kind: Deployment

metadata:
  name: tasks-api
  namespace: orbit

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tasks-api

  template:
    metadata:
      labels:
        app: tasks-api

    spec:
      containers:
        - name: tasks-api
          image: orbit-platform-tasks-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: SERVER_PORT
              value: "8000"

            - name: DB_HOST
              value: "postgresql"

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: "orbit"

            - name: DB_USER
              value: "orbit"

            - name: DB_PASSWORD
              value: "postgres"

            - name: INTERNS_API_URL
              value: "http://interns-api:8080"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi