apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: orbit

  source:
    repoURL: https://github.com/Yasmine-BH/orbit-platform.git
    targetRevision: main
    path: charts/tasks-api
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: orbit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
