{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasks-api.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  INTERNS_API_URL: {{ .Values.internsApi.url | quote }}
{{- end }}
